name: erv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.1=h81ee809_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=h6cefb37_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dnspython==2.7.0
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - fastapi==0.111.1
      - fastapi-cli==0.0.8
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - h11==0.16.0
      - h2==4.2.0
      - h5py==3.11.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - multidict==6.6.3
      - numpy==1.26.4
      - opencv-python-headless==4.9.0.80
      - packaging==25.0
      - pillow==11.3.0
      - priority==2.0.0
      - propcache==0.3.2
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyee==11.1.1
      - pygments==2.19.2
      - pynput==1.8.1
      - pyobjc==11.1
      - pyobjc-core==11.1
      - pyobjc-framework-accessibility==11.1
      - pyobjc-framework-accounts==11.1
      - pyobjc-framework-addressbook==11.1
      - pyobjc-framework-adservices==11.1
      - pyobjc-framework-adsupport==11.1
      - pyobjc-framework-applescriptkit==11.1
      - pyobjc-framework-applescriptobjc==11.1
      - pyobjc-framework-applicationservices==11.1
      - pyobjc-framework-apptrackingtransparency==11.1
      - pyobjc-framework-audiovideobridging==11.1
      - pyobjc-framework-authenticationservices==11.1
      - pyobjc-framework-automaticassessmentconfiguration==11.1
      - pyobjc-framework-automator==11.1
      - pyobjc-framework-avfoundation==11.1
      - pyobjc-framework-avkit==11.1
      - pyobjc-framework-avrouting==11.1
      - pyobjc-framework-backgroundassets==11.1
      - pyobjc-framework-browserenginekit==11.1
      - pyobjc-framework-businesschat==11.1
      - pyobjc-framework-calendarstore==11.1
      - pyobjc-framework-callkit==11.1
      - pyobjc-framework-carbon==11.1
      - pyobjc-framework-cfnetwork==11.1
      - pyobjc-framework-cinematic==11.1
      - pyobjc-framework-classkit==11.1
      - pyobjc-framework-cloudkit==11.1
      - pyobjc-framework-cocoa==11.1
      - pyobjc-framework-collaboration==11.1
      - pyobjc-framework-colorsync==11.1
      - pyobjc-framework-contacts==11.1
      - pyobjc-framework-contactsui==11.1
      - pyobjc-framework-coreaudio==11.1
      - pyobjc-framework-coreaudiokit==11.1
      - pyobjc-framework-corebluetooth==11.1
      - pyobjc-framework-coredata==11.1
      - pyobjc-framework-corehaptics==11.1
      - pyobjc-framework-corelocation==11.1
      - pyobjc-framework-coremedia==11.1
      - pyobjc-framework-coremediaio==11.1
      - pyobjc-framework-coremidi==11.1
      - pyobjc-framework-coreml==11.1
      - pyobjc-framework-coremotion==11.1
      - pyobjc-framework-coreservices==11.1
      - pyobjc-framework-corespotlight==11.1
      - pyobjc-framework-coretext==11.1
      - pyobjc-framework-corewlan==11.1
      - pyobjc-framework-cryptotokenkit==11.1
      - pyobjc-framework-datadetection==11.1
      - pyobjc-framework-devicecheck==11.1
      - pyobjc-framework-devicediscoveryextension==11.1
      - pyobjc-framework-dictionaryservices==11.1
      - pyobjc-framework-discrecording==11.1
      - pyobjc-framework-discrecordingui==11.1
      - pyobjc-framework-diskarbitration==11.1
      - pyobjc-framework-dvdplayback==11.1
      - pyobjc-framework-eventkit==11.1
      - pyobjc-framework-exceptionhandling==11.1
      - pyobjc-framework-executionpolicy==11.1
      - pyobjc-framework-extensionkit==11.1
      - pyobjc-framework-externalaccessory==11.1
      - pyobjc-framework-fileprovider==11.1
      - pyobjc-framework-fileproviderui==11.1
      - pyobjc-framework-findersync==11.1
      - pyobjc-framework-fsevents==11.1
      - pyobjc-framework-fskit==11.1
      - pyobjc-framework-gamecenter==11.1
      - pyobjc-framework-gamecontroller==11.1
      - pyobjc-framework-gamekit==11.1
      - pyobjc-framework-gameplaykit==11.1
      - pyobjc-framework-healthkit==11.1
      - pyobjc-framework-imagecapturecore==11.1
      - pyobjc-framework-inputmethodkit==11.1
      - pyobjc-framework-installerplugins==11.1
      - pyobjc-framework-instantmessage==11.1
      - pyobjc-framework-intents==11.1
      - pyobjc-framework-intentsui==11.1
      - pyobjc-framework-iobluetooth==11.1
      - pyobjc-framework-iobluetoothui==11.1
      - pyobjc-framework-iosurface==11.1
      - pyobjc-framework-ituneslibrary==11.1
      - pyobjc-framework-kernelmanagement==11.1
      - pyobjc-framework-latentsemanticmapping==11.1
      - pyobjc-framework-launchservices==11.1
      - pyobjc-framework-libdispatch==11.1
      - pyobjc-framework-libxpc==11.1
      - pyobjc-framework-linkpresentation==11.1
      - pyobjc-framework-localauthentication==11.1
      - pyobjc-framework-localauthenticationembeddedui==11.1
      - pyobjc-framework-mailkit==11.1
      - pyobjc-framework-mapkit==11.1
      - pyobjc-framework-mediaaccessibility==11.1
      - pyobjc-framework-mediaextension==11.1
      - pyobjc-framework-medialibrary==11.1
      - pyobjc-framework-mediaplayer==11.1
      - pyobjc-framework-mediatoolbox==11.1
      - pyobjc-framework-metal==11.1
      - pyobjc-framework-metalfx==11.1
      - pyobjc-framework-metalkit==11.1
      - pyobjc-framework-metalperformanceshaders==11.1
      - pyobjc-framework-metalperformanceshadersgraph==11.1
      - pyobjc-framework-metrickit==11.1
      - pyobjc-framework-mlcompute==11.1
      - pyobjc-framework-modelio==11.1
      - pyobjc-framework-multipeerconnectivity==11.1
      - pyobjc-framework-naturallanguage==11.1
      - pyobjc-framework-netfs==11.1
      - pyobjc-framework-network==11.1
      - pyobjc-framework-networkextension==11.1
      - pyobjc-framework-notificationcenter==11.1
      - pyobjc-framework-opendirectory==11.1
      - pyobjc-framework-osakit==11.1
      - pyobjc-framework-oslog==11.1
      - pyobjc-framework-passkit==11.1
      - pyobjc-framework-pencilkit==11.1
      - pyobjc-framework-phase==11.1
      - pyobjc-framework-photos==11.1
      - pyobjc-framework-photosui==11.1
      - pyobjc-framework-preferencepanes==11.1
      - pyobjc-framework-pushkit==11.1
      - pyobjc-framework-quartz==11.1
      - pyobjc-framework-quicklookthumbnailing==11.1
      - pyobjc-framework-replaykit==11.1
      - pyobjc-framework-safariservices==11.1
      - pyobjc-framework-safetykit==11.1
      - pyobjc-framework-scenekit==11.1
      - pyobjc-framework-screencapturekit==11.1
      - pyobjc-framework-screensaver==11.1
      - pyobjc-framework-screentime==11.1
      - pyobjc-framework-scriptingbridge==11.1
      - pyobjc-framework-searchkit==11.1
      - pyobjc-framework-security==11.1
      - pyobjc-framework-securityfoundation==11.1
      - pyobjc-framework-securityinterface==11.1
      - pyobjc-framework-securityui==11.1
      - pyobjc-framework-sensitivecontentanalysis==11.1
      - pyobjc-framework-servicemanagement==11.1
      - pyobjc-framework-sharedwithyou==11.1
      - pyobjc-framework-sharedwithyoucore==11.1
      - pyobjc-framework-shazamkit==11.1
      - pyobjc-framework-social==11.1
      - pyobjc-framework-soundanalysis==11.1
      - pyobjc-framework-speech==11.1
      - pyobjc-framework-spritekit==11.1
      - pyobjc-framework-storekit==11.1
      - pyobjc-framework-symbols==11.1
      - pyobjc-framework-syncservices==11.1
      - pyobjc-framework-systemconfiguration==11.1
      - pyobjc-framework-systemextensions==11.1
      - pyobjc-framework-threadnetwork==11.1
      - pyobjc-framework-uniformtypeidentifiers==11.1
      - pyobjc-framework-usernotifications==11.1
      - pyobjc-framework-usernotificationsui==11.1
      - pyobjc-framework-videosubscriberaccount==11.1
      - pyobjc-framework-videotoolbox==11.1
      - pyobjc-framework-virtualization==11.1
      - pyobjc-framework-vision==11.1
      - pyobjc-framework-webkit==11.1
      - pyparsing==3.2.3
      - pyppeteer==2.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.1.0
      - rich-toolkit==0.14.9
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.37.2
      - taskgroup==0.2.2
      - tomli==2.2.1
      - tqdm==4.67.1
      - typer==0.16.0
      - typing-extensions==4.14.1
      - urllib3==1.26.20
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==10.4
      - wsproto==1.2.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /Users/harsh/miniforge3/envs/erv
